name: ci
on: [push, pull_request]

jobs:
  ci: 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-latest
    steps:
      - name: Deno Setup ğŸ¦•
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - name: Node Setup ğŸŸ¢
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Create Artifacts Directory ğŸ“
        run: |
          mkdir -p ./.artifacts
        shell: bash

      - name: Deno Lint ğŸ”¥
        run: deno lint

      - name: Deno Test ğŸ§ª
        run: deno task test

      - name: Coverage ğŸ“Š
        run: deno task cov 
        if: runner.os == 'Linux'

      - name: Upload to Coveralls.io â«
        if: runner.os == 'Linux'
        # Any code coverage service can be used, Coveralls.io is used here as an example.
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Generated by GitHub.
          path-to-lcov: ./.artifacts/mod.lcov

      - name: Npm Install ğŸ“¦
        run: npm install
        working-directory: ./npm

      - name: Npm Test ğŸ§ª
        run: npm test
        working-directory: ./npm